### ISSUE TITLE
Create Webhook for Discord Notifications

### ISSUE THREAD

**Issue by FreakyNobleGas** [Wolfinbarger/game-recommender#1]
Since we currently use Discord to communicate on the project, we should create a webhook so that the team is notified for any updates to this repo.

Optionally, we could create multiple webhooks for different events. One idea would be to have a separate channel and webhook for pull requests and another for updates to issues.

**Comment by FreakyNobleGas** [comment]
@Wolfinbarger, I don't have access to the webhook settings for this repo, so we'll need you to kick this off.

**Comment by Wolfinbarger** [comment]
Will need access to discord channels to add webhooks. Aiming only for PR and issues or include branches?

**Comment by FreakyNobleGas** [comment]
I'm in favor of doing PR and Issues. I don't think I would find much value in branch notifications, but I'm also not against it.

**Comment by Wolfinbarger** [comment]
Webhooks enable in proper channel.
