### ISSUE TITLE
Update Settings for Committing to Main

### ISSUE THREAD

**Issue by FreakyNobleGas** [Wolfinbarger/game-recommender#2]
In the spirit of good git hygiene, we should add a protection rule to the main branch so that we cannot commit directly to it. 

Using PRs in our workflow has a lot of benefits. It allows us to document changes so we can reference them later and also keeps the team up to date on changes to the codebase.

**Comment by FreakyNobleGas** [comment]
@Wolfinbarger, since you're the owner of the repo, I think you'll need to add this branch protection rule.

**Comment by Wolfinbarger** [comment]
Resolved unless additional setting will be needed outside of 1 reviewer.
